sculpin_content_types:
    posts:
        enabled: false
#        permalink: blog/:year/:month/:day/:filename/

    publications:
      layout: publication
      permalink: publication/:slug_title.html
